apiVersion: v1
kind: Service
metadata:
  name: hello-world-golang
  labels:
    app: hello-world-golang
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080    
  selector:
    app: hello-world-golang
  type: ClusterIP
