apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-golang

spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: hello-world-golang
        image: docker.io/kamranazeem/hello-world-golang:1.0.3
        ports:
        - containerPort: 8080
