apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-golang
  labels:
    app: hello-world-golang
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world-golang
  template:
    metadata:
      labels:
        app: hello-world-golang
    spec:
      containers:
      - name: hello-world-golang
        image: docker.io/kamranazeem/hello-world-golang:v1.0.0
        ports:
        - containerPort: 8080
