apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: image-updater-hello-world-golang
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd-image-updater.argoproj.io/image-list: docker.io/kamranazeem/hello-world-golang:~1
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/github-credentials
    argocd-image-updater.argoproj.io/branch: master
spec:
  project: default
  source:
    repoURL: https://github.com/KamranAzeem/hello-world-golang-config.git
    targetRevision: HEAD
    path: kustomize/overlays/dev 
  destination:
    server: https://kubernetes.default.svc
    namespace: hello-world-golang
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
