resources:
- deployment.yaml
- service.yaml
- configmap.yaml

commonLabels:
  app: hello-world-golang

#~ commonAnnotations:
  #~ app: mykustom-annontations

#~ namePrefix:
  #~ kustom-

#~ nameSuffix:
  #~ -v1


